export const legalPages = {
  terms: {
    title: 'Terms of Service | IELTS AI Tutor by IELTSGRADER',
    description: 'Terms of Service for IELTS AI Tutor by IELTSGRADER: accounts, subscriptions, AI feedback limitations, acceptable use, and liability.',
    heading: 'Terms of Service',
    updatedAt: 'July 10, 2026',
    draft: false,
    sections: [
      {
        heading: '1. Agreement to these Terms',
        body: 'These Terms of Service (“Terms”) govern your access to and use of IELTS AI Tutor by IELTSGRADER at ieltsgrader.com and related applications, websites, and services (collectively, the “Service”). By creating an account, purchasing a plan, or using the Service, you agree to these Terms. If you do not agree, do not use the Service.',
      },
      {
        heading: '2. Who we are',
        body: 'IELTSGRADER operates IELTS AI Tutor, an AI-assisted writing evaluation and study-planning platform for IELTS preparation. The Service is an independent educational product. It is not affiliated with, endorsed by, or connected to IELTS, the British Council, IDP Education, or Cambridge Assessment English.',
      },
      {
        heading: '3. Eligibility',
        body: 'You must be at least 13 years old (or 16 where required by local law) to use the Service. If you use the Service on behalf of a school or organization, you represent that you have authority to bind that organization to these Terms.',
      },
      {
        heading: '4. The Service',
        body: 'The Service provides AI-powered IELTS writing evaluation (Academic and General Training Task 1 and Task 2), detailed feedback reports, mock writing exams, progress analytics, and personalized learning materials. Features may vary by plan. We may improve, add, or remove features with reasonable notice when changes are material.',
      },
      {
        heading: '5. Accounts and security',
        body: 'You must provide accurate registration information and keep your credentials confidential. You are responsible for activity under your account. Notify us promptly via account Settings → Support if you suspect unauthorized access. We may suspend accounts that pose security, fraud, or abuse risks.',
      },
      {
        heading: '6. Subscriptions, credits, and payments',
        body: 'New users may receive free evaluation credits as described on the site. Paid plans (for example Weekly Sprint and Monthly Mastery) and credit packs are billed according to the Pricing page and checkout terms. Payments are processed by Stripe. Fees are generally non-refundable except where required by law or expressly stated at purchase. Unused credits expire according to plan rules shown at checkout or in your subscription settings. Taxes may apply based on your location.',
      },
      {
        heading: '7. AI feedback limitations',
        body: 'Feedback is generated by automated systems aligned with publicly available IELTS band descriptors. Results are for practice and learning only. They are not official IELTS scores and do not guarantee any score on a real IELTS test. You remain responsible for your exam preparation and official registration.',
      },
      {
        heading: '8. Your content',
        body: 'You retain ownership of essays and files you submit. You grant us a worldwide, non-exclusive license to host, process, and analyze that content solely to operate, secure, and improve the Service (including generating reports and personalized learning materials). Do not submit content you do not have rights to, or content that is unlawful or infringing.',
      },
      {
        heading: '9. Acceptable use',
        items: [
          'Do not attempt to reverse-engineer, scrape, or overload the Service beyond normal interactive use.',
          'Do not use the Service to cheat on official exams or to misrepresent AI output as your unaided work where prohibited.',
          'Do not upload malware, harass others, or violate applicable laws.',
          'Do not resell access or share paid accounts without our written permission.',
        ],
      },
      {
        heading: '10. Intellectual property',
        body: 'The Service software, branding, UI, documentation, and original generated study materials (excluding your submitted essays) are owned by IELTSGRADER or its licensors. You may not copy, modify, or distribute them except as allowed by these Terms.',
      },
      {
        heading: '11. Privacy',
        body: 'Our collection and use of personal data is described in the Privacy Policy.',
        link: { href: '/privacy', label: 'Read the Privacy Policy' },
      },
      {
        heading: '12. Disclaimers',
        body: 'THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not warrant uninterrupted or error-free operation, or that AI feedback will match any official examiner’s judgment.',
      },
      {
        heading: '13. Limitation of liability',
        body: 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, IELTSGRADER AND ITS AFFILIATES WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, DATA, OR EXAM OUTCOMES. OUR TOTAL LIABILITY FOR CLAIMS ARISING OUT OF THE SERVICE IS LIMITED TO THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE (12) MONTHS BEFORE THE CLAIM.',
      },
      {
        heading: '14. Termination',
        body: 'You may stop using the Service and request account deletion via Settings or Support. We may suspend or terminate access for breach of these Terms, non-payment, or risk to the Service. Provisions that by nature should survive (including IP, disclaimers, and liability limits) will survive termination.',
      },
      {
        heading: '15. Changes',
        body: 'We may update these Terms. Material changes will be posted on this page with an updated date. Continued use after changes become effective constitutes acceptance.',
      },
      {
        heading: '16. Contact',
        body: 'Questions about these Terms: use Settings → Support in your account, or contact the support email published on the Service.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy | IELTS AI Tutor by IELTSGRADER',
    description: 'Privacy Policy for IELTS AI Tutor by IELTSGRADER: what data we collect, how we use it, processors, retention, and your rights.',
    heading: 'Privacy Policy',
    updatedAt: 'July 10, 2026',
    draft: false,
    sections: [
      {
        heading: '1. Introduction',
        body: 'This Privacy Policy explains how IELTSGRADER (“we”, “us”) collects, uses, and shares information when you use IELTS AI Tutor at ieltsgrader.com. By using the Service, you acknowledge this Policy.',
      },
      {
        heading: '2. Data we collect',
        items: [
          'Account data: name, email, password (hashed), optional profile image, preferences.',
          'Submission data: essay text, questions, uploaded files (PDF, Word, images), OCR-extracted text, task metadata.',
          'Report and learning data: band scores, feedback, study plans, learning editions.',
          'Payment data: processed by Stripe; we do not store full card numbers.',
          'Technical data: IP address, device/browser, pages visited, referral/UTM parameters, approximate location from IP.',
          'OAuth data: if you sign in with Google, we receive profile information according to Google’s policies and your permissions.',
        ],
      },
      {
        heading: '3. How we use data',
        items: [
          'Provide grading, reports, mock exams, and personalized learning.',
          'Authenticate users, secure accounts, and prevent fraud or abuse.',
          'Process subscriptions, credits, and customer support.',
          'Send transactional email (password reset, receipts).',
          'Analyze product usage to improve reliability and features.',
          'Comply with legal obligations.',
        ],
      },
      {
        heading: '4. AI processing',
        body: 'Essays and related inputs are processed by automated models to generate scores and feedback. Do not include highly sensitive personal data (for example government ID numbers or health details) in essays unless necessary for the writing task. AI outputs are practice tools, not official exam results.',
      },
      {
        heading: '5. Sharing and processors',
        body: 'We do not sell your personal data. We share data with service providers who help us operate the Service under contractual obligations, including: Supabase (database/auth storage), Stripe (payments), email delivery providers, Vercel (frontend hosting), and Fly.io (API hosting). We may disclose information if required by law or to protect rights, safety, and security.',
      },
      {
        heading: '6. Retention',
        body: 'We retain account and submission data while your account is active and as needed to provide the Service, resolve disputes, and meet legal requirements. You may request deletion; we will delete or anonymize personal data except where retention is required by law or for legitimate security/accounting records.',
      },
      {
        heading: '7. Your rights',
        body: 'Depending on your location (including GDPR/UK GDPR and CCPA/CPRA where applicable), you may have rights to access, correct, delete, export, or restrict processing of your personal data, and to object to certain processing. You may also withdraw consent where processing is consent-based. To exercise rights, use Settings or contact Support. You may lodge a complaint with a supervisory authority where applicable.',
      },
      {
        heading: '8. International transfers',
        body: 'We may process data in countries other than your own. Where required, we use appropriate safeguards for cross-border transfers.',
      },
      {
        heading: '9. Children',
        body: 'The Service is not directed to children under 13 (or under 16 in the EEA/UK where applicable). We do not knowingly collect personal data from children below those ages.',
      },
      {
        heading: '10. Cookies',
        body: 'We use cookies and similar technologies as described in our Cookie Policy.',
        link: { href: '/cookies', label: 'Read the Cookie Policy' },
      },
      {
        heading: '11. Security',
        body: 'We use industry-standard measures such as encryption in transit, access controls, and hashed passwords. No method of transmission or storage is 100% secure.',
      },
      {
        heading: '12. Changes',
        body: 'We may update this Policy and will post the revised version with an updated date. Material changes may be communicated via the Service or email when appropriate.',
      },
      {
        heading: '13. Contact',
        body: 'Privacy requests: Settings → Support in your account, or the support contact published on the Service.',
      },
    ],
  },
  cookies: {
    title: 'Cookie Policy | IELTS AI Tutor by IELTSGRADER',
    description: 'Cookie Policy for IELTS AI Tutor by IELTSGRADER: essential, functional, and analytics cookies, and how to manage them.',
    heading: 'Cookie Policy',
    updatedAt: 'July 10, 2026',
    draft: false,
    sections: [
      {
        heading: '1. What are cookies?',
        body: 'Cookies are small text files stored on your device when you visit a website. Similar technologies include local storage and pixels. This Policy explains how IELTSGRADER uses them on ieltsgrader.com.',
      },
      {
        heading: '2. Why we use cookies',
        body: 'We use cookies to keep you signed in, secure the Service, remember preferences, understand how the product is used, and support payment flows.',
      },
      {
        heading: '3. Types of cookies we use',
        items: [
          'Essential: authentication session, security, load balancing, and core functionality. The Service cannot work properly without these.',
          'Functional: remember UI preferences and similar settings where enabled.',
          'Analytics: help us understand traffic and feature usage so we can improve the product (only if analytics is enabled for your visit).',
          'Payment / fraud: Stripe may set cookies during checkout to process payments and prevent fraud.',
          'OAuth: Google may set cookies if you choose Google sign-in.',
        ],
      },
      {
        heading: '4. Cookie details (typical)',
        items: [
          'Session / auth tokens: identify your logged-in session (essential).',
          'CSRF / security cookies: protect forms and API requests (essential).',
          'Preference keys: store non-sensitive UI choices (functional).',
          'Attribution / UTM storage: remember how you found the Service for product analytics (analytics/functional).',
        ],
      },
      {
        heading: '5. Managing cookies',
        body: 'You can block or delete cookies in your browser settings. Blocking essential cookies may prevent login, checkout, or other core features. Where required by law, we will request consent for non-essential cookies.',
      },
      {
        heading: '6. Updates',
        body: 'We may update this Cookie Policy when our practices or providers change. The “Last updated” date at the top of the page reflects the latest revision.',
      },
      {
        heading: '7. Contact',
        body: 'Questions about cookies: Settings → Support, or the support contact published on the Service.',
      },
      {
        heading: 'Related policies',
        body: 'See also our Privacy Policy and Terms of Service.',
        link: { href: '/privacy', label: 'Privacy Policy' },
      },
    ],
  },
};
